### PR TITLE
Fix _getVerificationMethod

### PR DESCRIPTION
**Pull request by OR13**
Addresses #1

### CODE REVIEW

**Comment by OR13** [comment]
@dlongley This issue is currently blocking edv / github-did integration as well as element. Let me know if I can help address it some other way :)

**Comment by dlongley** [comment]
Pulled in via 0ce2277e4a9f08f690f4fc254e0ffb54ecafb475.

**Comment by dlongley** [comment]
Thanks, @OR13! I just pulled over a minimal change for now so we don't have to review/figure out the rest.

**Comment by OR13** [comment]
@dlongley awesome! sorry about the lint stuff, vscode prettier-ed it so in order to preserve your lint settings I needed to add that stuff, in retrospect I probably should have just nano-edited as you did.

**Pull request closed without merging**
